name: freelens
version: 0.1.2 # datasource=github-releases depName=freelensapp/freelens
title: Freelens
summary: Freelens
description: Freelens - FOSS IDE for Kubernetes
icon: icon.png

base: core20

grade: stable
confinement: strict

architectures:
  - build-on: amd64
    run-on: amd64
  - build-on: arm64
    run-on: arm64

parts:
  freelens:
    plugin: dump
    source: https://github.com/freelensapp/freelens/releases/download/v$SNAPCRAFT_PROJECT_VERSION/Freelens-$SNAPCRAFT_PROJECT_VERSION-linux-$SNAPCRAFT_ARCH_BUILD_FOR.deb
    source-type: deb
    stage-packages:
      - ca-certificates
      - gsettings-desktop-schemas
      - libasound2
      - libatk-bridge2.0-0
      - libatk1.0-0
      - libatspi2.0-0
      - libcairo2
      - libcanberra-gtk3-module
      - libcurl3-gnutls
      - libcurl3-nss
      - libcurl4
      - libdrm2
      - libegl1
      - libgbm1
      - libgdk-pixbuf2.0-0
      - libgl1
      - libgles2
      - libglib2.0-0
      - libglib2.0-bin
      - libgtk-3-0
      - libibus-1.0-5
      - libnotify4
      - libnss3
      - libpango-1.0-0
      - libsecret-1-0
      - libtiff5
      - libuuid1
      - libwayland-egl1
      - libxcomposite1
      - libxdamage1
      - libxfixes3
      - libxkbcommon0
      - libxkbfile1
      - libxrandr2
      - libxss1
      - libxtst6
      - locales-all
      - packagekit-gtk3-module
      - patchelf
      - xdg-utils
      - xkb-data
    stage-snaps:
      - aws-cli/v2/stable
    prime:
      - -opt/Freelens/chrome-sandbox
      - -usr/share/doc
      - -usr/share/fonts
      - -usr/share/icons
      - -usr/share/lintian
      - -usr/share/man
    override-build: |
      snapcraftctl build
      patchelf --force-rpath --set-rpath '$ORIGIN/../../lib/x86_64-linux-gnu:$ORIGIN:/snap/core20/current/lib/x86_64-linux-gnu' $SNAPCRAFT_PART_INSTALL/opt/Freelens/chrome_crashpad_handler
  gui:
    after:
      - freelens
    plugin: dump
    source: gui
  cleanup:
    after:
      - freelens
      - gui
    plugin: nil
    build-snaps:
      - core20
    override-prime: |
      patchelf --print-rpath $SNAPCRAFT_PRIME/opt/Freelens/chrome_crashpad_handler

plugs:
  dot-freelens:
    interface: personal-files
    write:
      - $HOME/.freelens
  dot-kube:
    interface: personal-files
    write:
      - $HOME/.kube
  etc-vulkan:
    interface: system-files
    read:
      - /etc/glvnd/egl_vendor.d
      - /etc/vulkan
  gnome-3-38-2004:
    default-provider: gnome-3-38-2004
    interface: content
    target: $SNAP/gnome-platform
  gtk-3-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/themes
  icon-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/icons
  sound-themes:
    default-provider: gtk-common-themes
    interface: content
    target: $SNAP/data-dir/sounds
  shmem:
    interface: shared-memory
    private: true

apps:
  freelens:
    common-id: app.freelens.Freelens
    command: freelens-launch
    desktop: freelens.desktop
    extensions:
      - gnome-3-38
    plugs:
      - browser-support
      - desktop
      - desktop-legacy
      - dot-freelens
      - dot-kube
      - etc-vulkan
      - gnome-3-38-2004
      - gtk-3-themes
      - icon-themes
      - gsettings
      - home
      - mount-observe
      - network
      - opengl
      - process-control
      - removable-media
      - shmem
      - sound-themes
      - udisks2
      - wayland
      - x11
